import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# =========================================================
# 1. PAGE CONFIGURATION
#    Sets the browser tab title and layout to "Wide" mode
# =========================================================
st.set_page_config(
    page_title="Intelligent Inventory Dashboard",
    page_icon="📦",
    layout="wide"
)

# Custom CSS for "KPI Cards" styling
st.markdown("""
<style>
    .metric-card {
        background-color: #f0f2f6;
        border-radius: 10px;
        padding: 20px;
    }
</style>
""", unsafe_allow_html=True)

# =========================================================
# 2. SIDEBAR - FILE UPLOAD & FILTERS
# =========================================================
st.sidebar.header("📂 Data & Filters")
st.sidebar.markdown("Upload the `final_dashboard_data.csv` generated by your model.")
uploaded_file = st.sidebar.file_uploader("Upload CSV", type=["csv"])

if uploaded_file is not None:
    # Load Data
    df = pd.read_csv(uploaded_file)
    
    # Ensure Date format
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])

    # --------------------------------------------------
    # DYNAMIC FILTERS (Make the dashboard interactive)
    # --------------------------------------------------
    st.sidebar.subheader("Filter Data")
    
    # Check if columns exist before filtering
    categories = df['Category'].unique() if 'Category' in df.columns else []
    regions = df['Region'].unique() if 'Region' in df.columns else []

    selected_category = st.sidebar.multiselect("Select Category", options=categories, default=categories)
    selected_region = st.sidebar.multiselect("Select Region", options=regions, default=regions)

    # Apply Filters
    if 'Category' in df.columns and 'Region' in df.columns:
        df_filtered = df[(df['Category'].isin(selected_category)) & (df['Region'].isin(selected_region))]
    else:
        df_filtered = df

    # =========================================================
    # 3. MAIN DASHBOARD HEADER & KPI METRICS
    # =========================================================
    st.title("📦 Intelligent Demand & Inventory Management System")
    st.markdown("### 📊 Executive Summary")
    
    # KPI CALCULATION
    total_sales = df_filtered['Units Sold'].sum() if 'Units Sold' in df_filtered.columns else 0
    total_revenue = (df_filtered['Units Sold'] * df_filtered['Price']).sum() if 'Price' in df_filtered.columns else 0
    
    # Calculate Critical Stock (Items that need immediate ordering)
    if 'Stock_Status' in df_filtered.columns:
        critical_items = df_filtered[df_filtered['Stock_Status'] == 'Critical Low'].shape[0]
    else:
        critical_items = 0

    # Display KPIs in 4 Columns
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Revenue", f"${total_revenue:,.0f}")
    col2.metric("Total Units Sold", f"{total_sales:,.0f}")
    col3.metric("Critical Low Stock", f"{critical_items} Items", delta="Action Needed", delta_color="inverse")
    
    # Accuracy Metric (if available)
    if 'Actual_Demand' in df_filtered.columns and 'Predicted_Demand' in df_filtered.columns:
        mae = abs(df_filtered['Actual_Demand'] - df_filtered['Predicted_Demand']).mean()
        col4.metric("Avg Prediction Error (MAE)", f"{mae:.1f} Units")

    st.markdown("---")

    # =========================================================
    # 4. TABBED LAYOUT (The "Professional" Look)
    # =========================================================
    tab1, tab2, tab3 = st.tabs(["📈 Forecasting", "📦 Inventory Health", "🚨 Reorder Actions"])

    # --- TAB 1: FORECASTING ---
    with tab1:
        st.subheader("Actual vs Predicted Demand Over Time")
        
        if 'Date' in df_filtered.columns:
            # Aggregate by Date for a cleaner line chart
            daily_trend = df_filtered.groupby('Date')[['Actual_Demand', 'Predicted_Demand']].sum().reset_index()
            
            # Interactive Line Chart
            fig_trend = px.line(daily_trend, x='Date', y=['Actual_Demand', 'Predicted_Demand'],
                                labels={'value': 'Units', 'variable': 'Metric'},
                                color_discrete_map={'Actual_Demand': '#1f77b4', 'Predicted_Demand': '#ff7f0e'},
                                height=400)
            fig_trend.update_layout(template="plotly_white", hovermode="x unified")
            st.plotly_chart(fig_trend, use_container_width=True)
        else:
            st.warning("Date column missing for trend analysis.")

    # --- TAB 2: INVENTORY HEALTH ---
    with tab2:
        col_left, col_right = st.columns([1, 2])
        
        with col_left:
            st.subheader("Stock Status Distribution")
            if 'Stock_Status' in df_filtered.columns:
                status_counts = df_filtered['Stock_Status'].value_counts().reset_index()
                status_counts.columns = ['Status', 'Count']
                
                # Donut Chart
                fig_pie = px.pie(status_counts, values='Count', names='Status', hole=0.4,
                                 color='Status',
                                 color_discrete_map={'Healthy':'green', 'Low Warning':'orange', 'Critical Low':'red'})
                st.plotly_chart(fig_pie, use_container_width=True)
        
        with col_right:
            st.subheader("Category Performance")
            if 'Category' in df_filtered.columns:
                cat_sales = df_filtered.groupby('Category')['Units Sold'].sum().reset_index()
                fig_bar = px.bar(cat_sales, x='Category', y='Units Sold', color='Units Sold', color_continuous_scale='Viridis')
                st.plotly_chart(fig_bar, use_container_width=True)

    # --- TAB 3: REORDER ACTIONS ---
    with tab3:
        st.subheader("📋 Suggested Purchase Orders")
        st.markdown("The AI recommends ordering these items **immediately** to prevent stockouts.")
        
        if 'Suggested_Order' in df_filtered.columns:
            # Filter only items that need ordering
            reorder_df = df_filtered[df_filtered['Suggested_Order'] > 0].copy()
            
            # Select relevant columns for the manager
            display_cols = ['Date', 'Product ID', 'Category', 'Inventory Level', 'Predicted_Demand', 'Reorder_Point', 'Suggested_Order']
            # Ensure columns exist
            display_cols = [c for c in display_cols if c in reorder_df.columns]
            
            # Sort by urgency (highest order needed)
            reorder_df = reorder_df.sort_values(by='Suggested_Order', ascending=False)
            
            st.dataframe(reorder_df[display_cols].style.background_gradient(subset=['Suggested_Order'], cmap="Reds"))
            
            # Download Button
            csv = reorder_df.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="⬇️ Download Order List as CSV",
                data=csv,
                file_name='purchase_order_list.csv',
                mime='text/csv',
            )
        else:
            st.info("No 'Suggested_Order' column found. Please ensure your model script generates this.")

else:
    # --------------------------------------------------
    # LANDING PAGE (When no file is uploaded)
    # --------------------------------------------------
    st.info("👈 Please upload the `final_dashboard_data.csv` file from the sidebar to start.")
    st.markdown("""
    ### How to use this dashboard:
    1. Run your **Random Forest Model** script to generate `final_dashboard_data.csv`.
    2. Drag and drop that file into the **Sidebar**.
    3. Explore the **Forecasts** and download the **Order List**.
    """)
